import Head from 'next/head';
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Philosophia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='A Study into: Nihilism & Existentialism' message='Two beliefs that are similar yet quite different.'/>
      <Slider slides={SliderData} />
    </div>
  );
}
